# file      : tests/path-entry/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}
libs += $stdmod_lib

exe{driver}: {hxx cxx}{*} $libs testscript
