# file      : tests/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

d = base64/ cpfile/ dir-iterator/ fdstream/ link/ manifest-parser/ \
    manifest-serializer/ manifest-roundtrip/ pager/ path/ prefix-map/ \
    process/ sha256/ small-vector/ strcase/ timestamp/ target-triplet/ \
    wildcard/

./: $d
include $d
