# file      : tests/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

d = dir-iterator/ path/ prefix-map/ sha256/ timestamp/ triplet/
.: $d
include $d
