# file      : tests/small-vector/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}

if ($cxx.features.modules && ($force_std_modules == true || $cxx.id != 'msvc'))
{
  import libs += libstd-modules%liba{std-modules}
  cxx.poptions += -D__cpp_lib_modules
}

exe{driver}: {hxx cxx}{*} $libs
