# file      : tests/small-vector/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}
libs += $stdmod_lib

exe{driver}: {hxx cxx}{*} $libs
