# file      : tests/sendmail/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{*} ../../libbutl/lib{butl} test{testscript}

include ../../libbutl/
