# file      : tests/manifest-rewriter/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}
libs += $stdmod_lib

exe{driver}: {hxx cxx}{*} $libs
