# file      : tests/fdstream/buildfile
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}

exe{driver}: {hxx cxx}{*} $libs

if ($cxx.target.class != "windows")
  cxx.libs += -pthread
