# file      : tests/timestamp/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{driver} ../../butl/lib{butl}

include ../../butl/
