# file      : tests/manifest-roundtrip/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{driver} ../../libbutl/lib{butl}
exe{driver}: test.roundtrip = manifest

include ../../libbutl/
