# file      : butl/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

lib{butl}: cxx{char-scanner fdstream filesystem path process timestamp}
cxx.poptions += -I$src_root
lib{butl}: cxx.export.poptions = -I$src_root
